
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'a b c dS : a A\n\t | b A\n\t | a S c\n\t | a S d\n\t | b S c\n\t | b S d\n\t | emptyA : a A\n\t | A b\n\t | a B\n\t | b B\n         | empty B : c B\n\t | B d\n         | empty empty :'
    
_lr_action_items = {'a':([0,2,3,5,8,],[2,5,5,5,5,]),'b':([0,2,3,5,6,8,9,10,12,13,14,15,16,19,20,23,24,25,],[3,8,8,8,16,8,-12,16,16,-10,-16,-12,-9,-11,-12,-14,-13,-15,]),'$end':([0,1,2,3,4,5,6,8,9,10,12,13,14,15,16,17,18,19,20,21,22,23,24,25,],[-16,0,-16,-16,-7,-16,-1,-16,-12,-2,-8,-10,-16,-12,-9,-3,-4,-11,-15,-5,-6,-14,-13,-15,]),'c':([2,3,5,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,],[-16,-16,14,17,14,-7,-2,21,-1,-10,14,-7,-9,-3,-4,-11,-7,-5,-6,-14,-13,-15,]),'d':([2,3,5,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,],[-16,-16,-16,18,-16,-7,-2,22,-1,23,-16,-7,-9,-3,-4,23,-7,-5,-6,-14,23,-15,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'S':([0,2,3,5,8,],[1,7,11,7,11,]),'empty':([0,2,3,5,8,14,],[4,9,9,15,20,25,]),'A':([2,3,5,8,],[6,10,12,10,]),'B':([5,8,14,],[13,19,24,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> S","S'",1,None,None,None),
  ('S -> a A','S',2,'p_S','2.py',16),
  ('S -> b A','S',2,'p_S','2.py',17),
  ('S -> a S c','S',3,'p_S','2.py',18),
  ('S -> a S d','S',3,'p_S','2.py',19),
  ('S -> b S c','S',3,'p_S','2.py',20),
  ('S -> b S d','S',3,'p_S','2.py',21),
  ('S -> empty','S',1,'p_S','2.py',22),
  ('A -> a A','A',2,'p_A','2.py',26),
  ('A -> A b','A',2,'p_A','2.py',27),
  ('A -> a B','A',2,'p_A','2.py',28),
  ('A -> b B','A',2,'p_A','2.py',29),
  ('A -> empty','A',1,'p_A','2.py',30),
  ('B -> c B','B',2,'p_B','2.py',34),
  ('B -> B d','B',2,'p_B','2.py',35),
  ('B -> empty','B',1,'p_B','2.py',36),
  ('empty -> <empty>','empty',0,'p_empty','2.py',40),
]
